spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

server:
    servlet:
      context-path: /sell

logging:
  pattern:
    console: "%d - %msg%n"
  file:
    path: "/var/log/"